### Step 1: Import necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2: Load the Data

In [2]:
cafe_DF = pd.read_csv('cafe_sales.csv')

### Step 3: Explore the Data

##### display the first 10 rows to see the "messy" data

In [3]:
cafe_DF.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

##### check how many rows and columns

In [4]:
cafe_DF.shape

(10000, 8)

##### display basic info about the dataset to identify nulls and incorrect data types

In [5]:
cafe_DF.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

##### check unique values for `Item`, `Payment Method`, and `Location`

In [6]:
cafe_DF['Item'].unique()
cafe_DF['Payment Method'].unique()
cafe_DF['Location'].unique()

<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

##### check missing values

In [7]:
cafe_DF.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

### Step 4: Handle Missing Values

##### Spot strings like "UNKNOWN" and "ERROR" that Pandas doesn't see as nulls yet

In [8]:
cafe_DF[(cafe_DF == 'UNKNOWN') | (cafe_DF == 'ERROR')]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,ERROR,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9995,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,NaN
9996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### Use `.replace()` to convert "UNKNOWN" and "ERROR" to np.nan

In [29]:
cafe_DF[(cafe_DF == 'UNKNOWN') | (cafe_DF == 'ERROR')]
cafe_DF = cafe_DF.replace(['UNKNOWN', 'ERROR'], np.nan)

### Step 5:Text Sanitization

##### remove hidden spaces from all string columns

In [27]:
cafe_DF = cafe_DF.apply(lambda col: col.str.strip() 
    if col.dtype == 'object' else col)

##### convert all Item names to lowercase for consistency

In [28]:
cafe_DF = cafe_DF.apply(lambda col: col.str.lower() 
   if col.dtype == 'object' else col)
cafe_DF.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total,Year,Month
0,txn_1961373,coffee,2.0,2.0,4.0,credit card,takeaway,2023-09-08,4.0,2023.0,9.0
1,txn_4977031,cake,4.0,3.0,12.0,cash,in-store,2023-05-16,12.0,2023.0,5.0
2,txn_4271903,cookie,4.0,1.0,4.0,credit card,in-store,2023-07-19,4.0,2023.0,7.0
3,txn_7034554,salad,2.0,5.0,10.0,digital wallet,takeaway,2023-04-27,10.0,2023.0,4.0
4,txn_3160411,coffee,2.0,2.0,4.0,digital wallet,in-store,2023-06-11,4.0,2023.0,6.0

##### use a dictionary to fix any typos in item names if they exist

In [13]:
print(cafe_DF['Item'].unique())
print(cafe_DF['Payment Method'].unique())
print(cafe_DF['Location'].unique())

#not found

<StringArray>
[  'coffee',     'cake',   'cookie',    'salad', 'smoothie',        nan,
 'sandwich',    'juice',      'tea']
Length: 9, dtype: str
<StringArray>
['credit card', 'cash', nan, 'digital wallet']
Length: 4, dtype: str
<StringArray>
['takeaway', 'in-store', nan]
Length: 3, dtype: str

### Step 6: Fix Data Types
##### fix incorrect data types (Quantity, Price Per Unit, Total Spent .....)

In [14]:
cafe_DF.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   str
 3   Price Per Unit    9467 non-null   str
 4   Total Spent       9498 non-null   str
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [15]:
cafe_DF['Quantity'] = pd.to_numeric(cafe_DF['Quantity'], errors='coerce')
cafe_DF['Price Per Unit'] = pd.to_numeric(cafe_DF['Price Per Unit'], errors='coerce')
cafe_DF['Total Spent'] = pd.to_numeric(cafe_DF['Total Spent'], errors='coerce')
#date 
cafe_DF['Transaction Date'] = pd.to_datetime(cafe_DF['Transaction Date'], errors='coerce')
cafe_DF.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB

##### identify and fix rows where Quantity might be zero or negative

In [30]:
cafe_DF.loc[cafe_DF['Quantity'] <= 0, 'Quantity'] = np.nan

### Step 7: Handle Missing Values (Part 2: Fill NaNs)

##### fill missing `Price Per Unit`

In [16]:

#fill it with the average
cafe_DF['Price Per Unit'] = cafe_DF['Price Per Unit'].fillna(cafe_DF['Price Per Unit'].mean())

In [17]:
cafe_DF['Price Per Unit'].isnull().sum()

np.int64(0)

##### handle other missing values appropriately (like Payment Method or Location)

In [19]:
cafe_DF[['Payment Method', 'Location']].isnull().sum()

Payment Method    3178
Location          3961
dtype: int64

In [20]:
# can use the most frequent val
cafe_DF["Payment Method"] = cafe_DF["Payment Method"].fillna(
    cafe_DF["Payment Method"].mode()[0]
)

cafe_DF["Location"] = cafe_DF["Location"].fillna(
    cafe_DF["Location"].mode()[0]
)


cafe_DF[['Payment Method', 'Location']].isnull().sum()

Payment Method    0
Location          0
dtype: int64

### Step 8: Logical Validation

##### create a new column `Expected_Total` by multiplying `Quantity * Price Per Unit`

In [21]:
cafe_DF['Expected_Total'] = cafe_DF['Quantity'] * cafe_DF['Price Per Unit']
cafe_DF.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total
0,txn_1961373,coffee,2.0,2.0,4.0,credit card,takeaway,2023-09-08,4.0
1,txn_4977031,cake,4.0,3.0,12.0,cash,in-store,2023-05-16,12.0
2,txn_4271903,cookie,4.0,1.0,NaN,credit card,in-store,2023-07-19,4.0
3,txn_7034554,salad,2.0,5.0,10.0,digital wallet,takeaway,2023-04-27,10.0
4,txn_3160411,coffee,2.0,2.0,4.0,digital wallet,in-store,2023-06-11,4.0

##### filter rows where Total Spent is NOT equal to Expected_Total

In [22]:
cafe_DF[cafe_DF['Total Spent'] != cafe_DF['Expected_Total']]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total
2,txn_4271903,cookie,4.0,1.000000,NaN,credit card,in-store,2023-07-19,4.000000
20,txn_3522028,smoothie,NaN,4.000000,20.0,cash,in-store,2023-04-04,NaN
25,txn_7958992,smoothie,3.0,4.000000,NaN,digital wallet,takeaway,2023-12-13,12.000000
31,txn_8927252,NaN,2.0,1.000000,NaN,credit card,takeaway,2023-11-06,2.000000
42,txn_6650263,tea,2.0,1.500000,NaN,digital wallet,takeaway,2023-01-10,3.000000
...,...,...,...,...,...,...,...,...,...
9984,txn_3142496,smoothie,NaN,4.000000,4.0,cash,takeaway,2023-07-27,NaN
9988,txn_9594133,cake,5.0,3.000000,NaN,digital wallet,takeaway,NaT,15.000000
9993,txn_4766549,smoothie,2.0,4.000000,NaN,cash,takeaway,2023-10-20,8.000000
9996,txn_9659401,NaN,3.0,2.949984,3.0,digital wallet,takeaway,2023-06-02,8.849952
9998,txn_7695629,cookie,3.0,2.949984,3.0,digital wallet,takeaway,2023-12-02,8.849952

##### fill missing or incorrect Total Spent values using the Expected_Total calculation.

In [23]:
cafe_DF['Total Spent'] = cafe_DF['Expected_Total']
cafe_DF[['Total Spent', 'Expected_Total']].head()

   Total Spent  Expected_Total
0          4.0             4.0
1         12.0            12.0
2          4.0             4.0
3         10.0            10.0
4          4.0             4.0

### Step 9: Handle Dates

##### convert Transaction Date to datetime

In [24]:
#already did 
cafe_DF.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       9521 non-null   float64
 5   Payment Method    10000 non-null  str
 6   Location          10000 non-null  str
 7   Transaction Date  9540 non-null   datetime64[us]
 8   Expected_Total    9521 non-null   float64
dtypes: datetime64[us](1), float64(4), str(4)
memory usage: 703.3 KB

##### identify transactions with dates in the future (if any) and handle them

In [ ]:
max_d = cafe_DF['Transaction Date'].max()
cafe_DF.loc[cafe_DF['Transaction Date'] > pd.Timestamp.today(), 'Transaction Date'] = max_d

##### extract "Year" and "Month" into separate columns for analysis

In [25]:
cafe_DF['Year'] = cafe_DF['Transaction Date'].dt.year
cafe_DF['Month'] = cafe_DF['Transaction Date'].dt.month
cafe_DF.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total,Year,Month
0,txn_1961373,coffee,2.0,2.0,4.0,credit card,takeaway,2023-09-08,4.0,2023.0,9.0
1,txn_4977031,cake,4.0,3.0,12.0,cash,in-store,2023-05-16,12.0,2023.0,5.0
2,txn_4271903,cookie,4.0,1.0,4.0,credit card,in-store,2023-07-19,4.0,2023.0,7.0
3,txn_7034554,salad,2.0,5.0,10.0,digital wallet,takeaway,2023-04-27,10.0,2023.0,4.0
4,txn_3160411,coffee,2.0,2.0,4.0,digital wallet,in-store,2023-06-11,4.0,2023.0,6.0

### Step 10: Remove Duplicates

##### check for duplicates

In [26]:
cafe_DF.duplicated().sum()

np.int64(0)

##### drop duplicates if found

In [ ]:
#0

### Step 9: Clean Text Data

#####  clean text columns (strip spaces, unify format)

In [ ]:
#done -> strip , .lower