In [10]:
import pandas as pd

to read data ?
read_csv()

In [11]:
learn__D = pd.read_csv("chipotle.csv")
learn__D #just an overview of the data

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

to know how the data looks like ?
num(rows , coulmn)

In [12]:
learn__D.shape

(4622, 5)

to be more info ?
like the data types ?
.info()

In [13]:
learn__D.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

n(rows)?
shape[0]
n(columns)?
shape[1]

In [14]:
learn__D.shape[0]

4622

In [15]:
learn__D.shape[1]

5

Series vs data frame?

Series is a one-dimensional labeled array (like a single column)

DataFrame is a 2-dimensional table made up of multiple Series (rows and columns)

In [18]:
# to access multiple columns  
learn__D[['item_name', 'quantity']]

                                  item_name  quantity
0              Chips and Fresh Tomato Salsa         1
1                                      Izze         1
2                          Nantucket Nectar         1
3     Chips and Tomatillo-Green Chili Salsa         1
4                              Chicken Bowl         2
...                                     ...       ...
4617                          Steak Burrito         1
4618                          Steak Burrito         1
4619                     Chicken Salad Bowl         1
4620                     Chicken Salad Bowl         1
4621                     Chicken Salad Bowl         1

[4622 rows x 2 columns]

iloc vs loc ?

In [21]:
# iloc -> to access by index (integer location)
learn__D.iloc[[0, 1], [0, 1, 2]] # access the first two rows and the first three columns

   order_id  quantity                     item_name
0         1         1  Chips and Fresh Tomato Salsa
1         1         1                          Izze

In [23]:
# loc -> to access by label (column name)
learn__D.loc[[0, 1], ['order_id', 'quantity','item_name']]

   order_id  quantity                     item_name
0         1         1  Chips and Fresh Tomato Salsa
1         1         1                          Izze

slicing ? 
buttt here it is inclusive

In [ ]:
#inclusive of the last index
learn__D.loc[0:3, 'order_id':'item_name']

   order_id  quantity                              item_name
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa

filter rows and columns

In [ ]:
learn__D['item_name']== 'Izze'
# this returns true false values but to get the actual rows we can assign it to a variable

0       False
1        True
2       False
3       False
4       False
        ...
4617    False
4618    False
4619    False
4620    False
4621    False
Name: item_name, Length: 4622, dtype: bool

In [48]:
is_Izze = learn__D['item_name']== 'Izze'
learn__D[is_Izze]

      order_id  quantity item_name choice_description item_price
1            1         1      Izze       [Clementine]     $3.39
24          12         1      Izze       [Grapefruit]     $3.39
47          21         1      Izze       [Blackberry]     $3.39
66          30         1      Izze       [Blackberry]     $3.39
359        155         1      Izze       [Blackberry]     $3.39
360        155         1      Izze       [Grapefruit]     $3.39
430        186         1      Izze       [Grapefruit]     $3.39
579        237         1      Izze       [Clementine]     $3.39
580        237         1      Izze       [Grapefruit]     $3.39
1059       436         1      Izze       [Clementine]     $3.39
1213       495         1      Izze       [Clementine]     $3.39
1611       651         1      Izze       [Blackberry]     $3.39
1612       651         1      Izze       [Blackberry]     $3.39
1680       680         1      Izze       [Clementine]     $3.39
2088       842         1      Izze       [Clementine]     $3.39
2619      1040         1      Izze       [Clementine]     $3.39
2634      1046         1      Izze       [Clementine]     $3.39
2758      1095         1      Izze       [Blackberry]     $3.39
2891      1149         1      Izze       [Blackberry]     $3.39
3669      1468         1      Izze       [Blackberry]     $3.39

In [50]:
# or we can use .loc so we can get the columns we want
learn__D.loc[is_Izze , ['order_id', 'quantity']]

      order_id  quantity
1            1         1
24          12         1
47          21         1
66          30         1
359        155         1
360        155         1
430        186         1
579        237         1
580        237         1
1059       436         1
1213       495         1
1611       651         1
1612       651         1
1680       680         1
2088       842         1
2619      1040         1
2634      1046         1
2758      1095         1
2891      1149         1
3669      1468         1

In [52]:
#  '~' to negate the condition
learn__D.loc[~is_Izze]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

update columns

In [53]:
learn__D.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [54]:
learn__D.columns=['order_id', 'quantity', 'the_item_name', 'choice_description','item_price']

In [55]:
learn__D.columns

Index(['order_id', 'quantity', 'the_item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [ ]:
learn__D.columns=[i.upper() for i in learn__D.columns]
learn__D.columns

Index(['ORDER_ID', 'QUANTITY', 'THE_ITEM_NAME', 'CHOICE_DESCRIPTION',
       'ITEM_PRICE'],
      dtype='str')

modifying values

In [ ]:

# learn__D.loc[1,['THE_ITEM_NAME']]=['notIzze']
# learn__D.loc[1]

ORDER_ID                         1
QUANTITY                         1
THE_ITEM_NAME              notIzze
CHOICE_DESCRIPTION    [Clementine]
ITEM_PRICE                  $3.39
Name: 1, dtype: object

.apply()??
takes functions

In [69]:
learn__D.apply(pd.Series.min)
#the min val in each column

ORDER_ID                                                              1
QUANTITY                                                              1
THE_ITEM_NAME                                         6 Pack Soft Drink
CHOICE_DESCRIPTION    [Adobo-Marinated and Grilled Chicken, Pinto Be...
ITEM_PRICE                                                       $1.09
dtype: object

map vs replace

replace will keep the values we did not change as it is 
While map will return them as NaN

How to add and remove columns ?

In [72]:
learn__D.columns=[i.lower() for i in learn__D.columns]
learn__D.columns

Index(['order_id', 'quantity', 'the_item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [77]:
#convert price to float 
learn__D['item_price'] = learn__D['item_price'].str.replace('$', '').astype(float)

In [89]:
learn__D['total_price'] = learn__D['quantity'] * learn__D['item_price']
learn__D

,order_id,quantity,the_item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,notIzze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

remove the column

In [91]:
learn__D.drop('total_price', axis=1)

,order_id,quantity,the_item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,notIzze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [92]:
learn__D=learn__D.drop('total_price', axis=1, inplace=True)

In [95]:
learn__D.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

add row using pd.concat

In [100]:
new_row = pd.DataFrame([[4623,2,'Pizza','v', 10]], columns=learn__D.columns)
learn__D = pd.concat([learn__D, new_row], ignore_index=True)

In [101]:
learn__D.tail(1)

      order_id  quantity item_name choice_description item_price
4623      4623         2     Pizza                  v         10

In [102]:
learn__D.head(3)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39

In [103]:
learn__D.drop(1)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
...,...,...,...,...,...
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75
4622,4622,200,Pizza,2,10
4623,4623,2,Pizza,v,10

Sorting data ??

In [105]:
learn__D.sort_values('quantity')

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4492,1787,1,Chicken Burrito,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
...,...,...,...,...,...
3599,1443,7,Bottled Water,NaN,$10.50
3887,1559,8,Side of Chips,NaN,$13.52
4152,1660,10,Bottled Water,NaN,$15.00
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25
4622,4622,200,Pizza,2,10

In [106]:
#ascending is the default so to sort in descending order
learn__D.sort_values('quantity', ascending=False)

,order_id,quantity,item_name,choice_description,item_price
4622,4622,200,Pizza,2,10
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25
4152,1660,10,Bottled Water,NaN,$15.00
3887,1559,8,Side of Chips,NaN,$13.52
3599,1443,7,Bottled Water,NaN,$10.50
...,...,...,...,...,...
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75
146,65,1,Chips and Guacamole,NaN,$4.45
4045,1618,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$8.75